x-airflow-common: &airflow-common
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    environment:
      POSTGRES_EXTERNAL_PORT: ${POSTGRES_EXTERNAL_PORT}

    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  fastapi-app:
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile